SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN PUSHBUTTON (14) btn_1 USER-COMMAND btn_1.
SELECTION-SCREEN END OF LINE.

INITIALIZATION.
  btn_1 = 'Obj. no usados'.

AT SELECTION-SCREEN.

  CASE sscrfields-ucomm.
    WHEN 'BTN_1'. PERFORM buscar_refer.
  ENDCASE.